### ISSUE TITLE
Close game if host leaves

### ISSUE THREAD

**Issue by 1-alex98** [micheljung/faf-java-server#64]

**Comment by Brutus5000** [comment]
I would not use that feature. Make it optional.

**Comment by 1-alex98** [comment]
Host leaving game is correctly detected, but server should close game then.

**Comment by 1-alex98** [comment]
What was the outcome of our investigation

**Comment by micheljung** [comment]
Why has this been closed?

**Comment by 1-alex98** [comment]
U solved that no?

**Comment by micheljung** [comment]
Maybe, I wouldn't know :P
